/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class Lab8 */

#ifndef _Included_Lab8
#define _Included_Lab8
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     Lab8
 * Method:    calculateMean
 * Signature: ([I)D
 */
JNIEXPORT jdouble JNICALL Java_Lab8_calculateMean
  (JNIEnv *, jobject, jintArray);

/*
 * Class:     Lab8
 * Method:    calculateSTDDev
 * Signature: ([I)D
 */
JNIEXPORT jdouble JNICALL Java_Lab8_calculateSTDDev
  (JNIEnv *, jobject, jintArray);

#ifdef __cplusplus
}
#endif
#endif
